apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: lab-api-service
  namespace: default
spec:
  owner:
    projectName: latency-lab

  componentType:
    kind: ClusterComponentType
    name: deployment/service

  autoDeploy: true

  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/yashodgayashan/openchoreo-samples"
        revision:
          branch: "main"
        appPath: "/project-latency-lab/api-service"
      docker:
        context: "/project-latency-lab/api-service"
        filePath: "/project-latency-lab/api-service/Dockerfile"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: lab-api-service-build-01
  labels:
    openchoreo.dev/project: "latency-lab"
    openchoreo.dev/component: "lab-api-service"
spec:
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/yashodgayashan/openchoreo-samples"
        revision:
          branch: "main"
        appPath: "/project-latency-lab/api-service"
      docker:
        context: "/project-latency-lab/api-service"
        filePath: "/project-latency-lab/api-service/Dockerfile"
