apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: lab-redis
  namespace: default
spec:
  owner:
    projectName: latency-lab

  componentType:
    kind: ClusterComponentType
    name: deployment/service

  autoDeploy: true

  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/openchoreo-trace"
        revision:
          branch: "main"
        appPath: "/project-latency-lab/redis"
      docker:
        context: "/project-latency-lab/redis"
        filePath: "/project-latency-lab/redis/Dockerfile"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: lab-redis-build-01
  labels:
    openchoreo.dev/project: "latency-lab"
    openchoreo.dev/component: "lab-redis"
spec:
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/openchoreo-trace"
        revision:
          branch: "main"
        appPath: "/project-latency-lab/redis"
      docker:
        context: "/project-latency-lab/redis"
        filePath: "/project-latency-lab/redis/Dockerfile"
